// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: runetale/runetale/v1/admin.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Protos {

  /// <summary>Holder for reflection information generated from runetale/runetale/v1/admin.proto</summary>
  public static partial class AdminReflection {

    #region Descriptor
    /// <summary>File descriptor for runetale/runetale/v1/admin.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static AdminReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CiBydW5ldGFsZS9ydW5ldGFsZS92MS9hZG1pbi5wcm90bxIGcHJvdG9zQgla",
            "By4vYWRtaW5iBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, null, null));
    }
    #endregion

  }
}

#endregion Designer generated code
