// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: runetale/runetale/v1/login.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Protos {

  /// <summary>Holder for reflection information generated from runetale/runetale/v1/login.proto</summary>
  public static partial class LoginReflection {

    #region Descriptor
    /// <summary>File descriptor for runetale/runetale/v1/login.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static LoginReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CiBydW5ldGFsZS9ydW5ldGFsZS92MS9sb2dpbi5wcm90bxIGcHJvdG9zGhtn",
            "b29nbGUvcHJvdG9idWYvZW1wdHkucHJvdG8ixAEKEUxvZ2luTm9kZVJlc3Bv",
            "bnNlEhQKDGlzUmVnaXN0ZXJlZBgBIAEoCBIQCghsb2dpblVybBgCIAEoCRIK",
            "CgJpcBgDIAMoCRIMCgRjaWRyGAQgASgJEhIKCnNpZ25hbEhvc3QYBSABKAkS",
            "EgoKc2lnbmFsUG9ydBgGIAEoBBIOCgZ1c2VySWQYByABKAQSDQoFZW1haWwY",
            "CCABKAkSEwoLZGlzcGxheU5hbWUYCSABKAkSEQoJbG9naW5OYW1lGAogASgJ",
            "IpQBChRMb2dpblNlc3Npb25SZXNwb25zZRIKCgJpcBgBIAMoCRIMCgRjaWRy",
            "GAIgASgJEgwKBGhvc3QYAyABKAkSCgoCb3MYBCABKAkSFAoMY29tcHV0ZXJO",
            "YW1lGAUgASgJEhgKEHNpZ25hbFNlcnZlckhvc3QYBiABKAkSGAoQc2lnbmFs",
            "U2VydmVyUG9ydBgHIAEoBCIqChRHZXRJbnZpdGF0aW9uUmVxdWVzdBISCgpp",
            "bnZpdGVDb2RlGAEgASgJIjoKFUdldEludml0YXRpb25SZXNwb25zZRINCgVl",
            "bWFpbBgBIAEoCRISCgppbnZpdGVDb2RlGAIgASgJMqgCCgxMb2dpblNlcnZp",
            "Y2USQAoJTG9naW5Ob2RlEhYuZ29vZ2xlLnByb3RvYnVmLkVtcHR5GhkucHJv",
            "dG9zLkxvZ2luTm9kZVJlc3BvbnNlIgASOgoGTG9nb3V0EhYuZ29vZ2xlLnBy",
            "b3RvYnVmLkVtcHR5GhYuZ29vZ2xlLnByb3RvYnVmLkVtcHR5IgASSgoMTG9n",
            "aW5TZXNzaW9uEhYuZ29vZ2xlLnByb3RvYnVmLkVtcHR5GhwucHJvdG9zLkxv",
            "Z2luU2Vzc2lvblJlc3BvbnNlIgAoATABEk4KDUdldEludml0YXRpb24SHC5w",
            "cm90b3MuR2V0SW52aXRhdGlvblJlcXVlc3QaHS5wcm90b3MuR2V0SW52aXRh",
            "dGlvblJlc3BvbnNlIgBCCVoHLi9sb2dpbmIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Google.Protobuf.WellKnownTypes.EmptyReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Protos.LoginNodeResponse), global::Protos.LoginNodeResponse.Parser, new[]{ "IsRegistered", "LoginUrl", "Ip", "Cidr", "SignalHost", "SignalPort", "UserId", "Email", "DisplayName", "LoginName" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Protos.LoginSessionResponse), global::Protos.LoginSessionResponse.Parser, new[]{ "Ip", "Cidr", "Host", "Os", "ComputerName", "SignalServerHost", "SignalServerPort" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Protos.GetInvitationRequest), global::Protos.GetInvitationRequest.Parser, new[]{ "InviteCode" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Protos.GetInvitationResponse), global::Protos.GetInvitationResponse.Parser, new[]{ "Email", "InviteCode" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class LoginNodeResponse : pb::IMessage<LoginNodeResponse>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<LoginNodeResponse> _parser = new pb::MessageParser<LoginNodeResponse>(() => new LoginNodeResponse());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<LoginNodeResponse> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Protos.LoginReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public LoginNodeResponse() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public LoginNodeResponse(LoginNodeResponse other) : this() {
      isRegistered_ = other.isRegistered_;
      loginUrl_ = other.loginUrl_;
      ip_ = other.ip_.Clone();
      cidr_ = other.cidr_;
      signalHost_ = other.signalHost_;
      signalPort_ = other.signalPort_;
      userId_ = other.userId_;
      email_ = other.email_;
      displayName_ = other.displayName_;
      loginName_ = other.loginName_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public LoginNodeResponse Clone() {
      return new LoginNodeResponse(this);
    }

    /// <summary>Field number for the "isRegistered" field.</summary>
    public const int IsRegisteredFieldNumber = 1;
    private bool isRegistered_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool IsRegistered {
      get { return isRegistered_; }
      set {
        isRegistered_ = value;
      }
    }

    /// <summary>Field number for the "loginUrl" field.</summary>
    public const int LoginUrlFieldNumber = 2;
    private string loginUrl_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string LoginUrl {
      get { return loginUrl_; }
      set {
        loginUrl_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "ip" field.</summary>
    public const int IpFieldNumber = 3;
    private static readonly pb::FieldCodec<string> _repeated_ip_codec
        = pb::FieldCodec.ForString(26);
    private readonly pbc::RepeatedField<string> ip_ = new pbc::RepeatedField<string>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<string> Ip {
      get { return ip_; }
    }

    /// <summary>Field number for the "cidr" field.</summary>
    public const int CidrFieldNumber = 4;
    private string cidr_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Cidr {
      get { return cidr_; }
      set {
        cidr_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "signalHost" field.</summary>
    public const int SignalHostFieldNumber = 5;
    private string signalHost_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string SignalHost {
      get { return signalHost_; }
      set {
        signalHost_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "signalPort" field.</summary>
    public const int SignalPortFieldNumber = 6;
    private ulong signalPort_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ulong SignalPort {
      get { return signalPort_; }
      set {
        signalPort_ = value;
      }
    }

    /// <summary>Field number for the "userId" field.</summary>
    public const int UserIdFieldNumber = 7;
    private ulong userId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ulong UserId {
      get { return userId_; }
      set {
        userId_ = value;
      }
    }

    /// <summary>Field number for the "email" field.</summary>
    public const int EmailFieldNumber = 8;
    private string email_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Email {
      get { return email_; }
      set {
        email_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "displayName" field.</summary>
    public const int DisplayNameFieldNumber = 9;
    private string displayName_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string DisplayName {
      get { return displayName_; }
      set {
        displayName_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "loginName" field.</summary>
    public const int LoginNameFieldNumber = 10;
    private string loginName_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string LoginName {
      get { return loginName_; }
      set {
        loginName_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as LoginNodeResponse);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(LoginNodeResponse other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (IsRegistered != other.IsRegistered) return false;
      if (LoginUrl != other.LoginUrl) return false;
      if(!ip_.Equals(other.ip_)) return false;
      if (Cidr != other.Cidr) return false;
      if (SignalHost != other.SignalHost) return false;
      if (SignalPort != other.SignalPort) return false;
      if (UserId != other.UserId) return false;
      if (Email != other.Email) return false;
      if (DisplayName != other.DisplayName) return false;
      if (LoginName != other.LoginName) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (IsRegistered != false) hash ^= IsRegistered.GetHashCode();
      if (LoginUrl.Length != 0) hash ^= LoginUrl.GetHashCode();
      hash ^= ip_.GetHashCode();
      if (Cidr.Length != 0) hash ^= Cidr.GetHashCode();
      if (SignalHost.Length != 0) hash ^= SignalHost.GetHashCode();
      if (SignalPort != 0UL) hash ^= SignalPort.GetHashCode();
      if (UserId != 0UL) hash ^= UserId.GetHashCode();
      if (Email.Length != 0) hash ^= Email.GetHashCode();
      if (DisplayName.Length != 0) hash ^= DisplayName.GetHashCode();
      if (LoginName.Length != 0) hash ^= LoginName.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (IsRegistered != false) {
        output.WriteRawTag(8);
        output.WriteBool(IsRegistered);
      }
      if (LoginUrl.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(LoginUrl);
      }
      ip_.WriteTo(output, _repeated_ip_codec);
      if (Cidr.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(Cidr);
      }
      if (SignalHost.Length != 0) {
        output.WriteRawTag(42);
        output.WriteString(SignalHost);
      }
      if (SignalPort != 0UL) {
        output.WriteRawTag(48);
        output.WriteUInt64(SignalPort);
      }
      if (UserId != 0UL) {
        output.WriteRawTag(56);
        output.WriteUInt64(UserId);
      }
      if (Email.Length != 0) {
        output.WriteRawTag(66);
        output.WriteString(Email);
      }
      if (DisplayName.Length != 0) {
        output.WriteRawTag(74);
        output.WriteString(DisplayName);
      }
      if (LoginName.Length != 0) {
        output.WriteRawTag(82);
        output.WriteString(LoginName);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (IsRegistered != false) {
        output.WriteRawTag(8);
        output.WriteBool(IsRegistered);
      }
      if (LoginUrl.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(LoginUrl);
      }
      ip_.WriteTo(ref output, _repeated_ip_codec);
      if (Cidr.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(Cidr);
      }
      if (SignalHost.Length != 0) {
        output.WriteRawTag(42);
        output.WriteString(SignalHost);
      }
      if (SignalPort != 0UL) {
        output.WriteRawTag(48);
        output.WriteUInt64(SignalPort);
      }
      if (UserId != 0UL) {
        output.WriteRawTag(56);
        output.WriteUInt64(UserId);
      }
      if (Email.Length != 0) {
        output.WriteRawTag(66);
        output.WriteString(Email);
      }
      if (DisplayName.Length != 0) {
        output.WriteRawTag(74);
        output.WriteString(DisplayName);
      }
      if (LoginName.Length != 0) {
        output.WriteRawTag(82);
        output.WriteString(LoginName);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (IsRegistered != false) {
        size += 1 + 1;
      }
      if (LoginUrl.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(LoginUrl);
      }
      size += ip_.CalculateSize(_repeated_ip_codec);
      if (Cidr.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Cidr);
      }
      if (SignalHost.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(SignalHost);
      }
      if (SignalPort != 0UL) {
        size += 1 + pb::CodedOutputStream.ComputeUInt64Size(SignalPort);
      }
      if (UserId != 0UL) {
        size += 1 + pb::CodedOutputStream.ComputeUInt64Size(UserId);
      }
      if (Email.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Email);
      }
      if (DisplayName.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(DisplayName);
      }
      if (LoginName.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(LoginName);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(LoginNodeResponse other) {
      if (other == null) {
        return;
      }
      if (other.IsRegistered != false) {
        IsRegistered = other.IsRegistered;
      }
      if (other.LoginUrl.Length != 0) {
        LoginUrl = other.LoginUrl;
      }
      ip_.Add(other.ip_);
      if (other.Cidr.Length != 0) {
        Cidr = other.Cidr;
      }
      if (other.SignalHost.Length != 0) {
        SignalHost = other.SignalHost;
      }
      if (other.SignalPort != 0UL) {
        SignalPort = other.SignalPort;
      }
      if (other.UserId != 0UL) {
        UserId = other.UserId;
      }
      if (other.Email.Length != 0) {
        Email = other.Email;
      }
      if (other.DisplayName.Length != 0) {
        DisplayName = other.DisplayName;
      }
      if (other.LoginName.Length != 0) {
        LoginName = other.LoginName;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            IsRegistered = input.ReadBool();
            break;
          }
          case 18: {
            LoginUrl = input.ReadString();
            break;
          }
          case 26: {
            ip_.AddEntriesFrom(input, _repeated_ip_codec);
            break;
          }
          case 34: {
            Cidr = input.ReadString();
            break;
          }
          case 42: {
            SignalHost = input.ReadString();
            break;
          }
          case 48: {
            SignalPort = input.ReadUInt64();
            break;
          }
          case 56: {
            UserId = input.ReadUInt64();
            break;
          }
          case 66: {
            Email = input.ReadString();
            break;
          }
          case 74: {
            DisplayName = input.ReadString();
            break;
          }
          case 82: {
            LoginName = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            IsRegistered = input.ReadBool();
            break;
          }
          case 18: {
            LoginUrl = input.ReadString();
            break;
          }
          case 26: {
            ip_.AddEntriesFrom(ref input, _repeated_ip_codec);
            break;
          }
          case 34: {
            Cidr = input.ReadString();
            break;
          }
          case 42: {
            SignalHost = input.ReadString();
            break;
          }
          case 48: {
            SignalPort = input.ReadUInt64();
            break;
          }
          case 56: {
            UserId = input.ReadUInt64();
            break;
          }
          case 66: {
            Email = input.ReadString();
            break;
          }
          case 74: {
            DisplayName = input.ReadString();
            break;
          }
          case 82: {
            LoginName = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class LoginSessionResponse : pb::IMessage<LoginSessionResponse>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<LoginSessionResponse> _parser = new pb::MessageParser<LoginSessionResponse>(() => new LoginSessionResponse());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<LoginSessionResponse> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Protos.LoginReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public LoginSessionResponse() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public LoginSessionResponse(LoginSessionResponse other) : this() {
      ip_ = other.ip_.Clone();
      cidr_ = other.cidr_;
      host_ = other.host_;
      os_ = other.os_;
      computerName_ = other.computerName_;
      signalServerHost_ = other.signalServerHost_;
      signalServerPort_ = other.signalServerPort_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public LoginSessionResponse Clone() {
      return new LoginSessionResponse(this);
    }

    /// <summary>Field number for the "ip" field.</summary>
    public const int IpFieldNumber = 1;
    private static readonly pb::FieldCodec<string> _repeated_ip_codec
        = pb::FieldCodec.ForString(10);
    private readonly pbc::RepeatedField<string> ip_ = new pbc::RepeatedField<string>();
    /// <summary>
    /// host ip
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<string> Ip {
      get { return ip_; }
    }

    /// <summary>Field number for the "cidr" field.</summary>
    public const int CidrFieldNumber = 2;
    private string cidr_ = "";
    /// <summary>
    /// host wireguard cidr
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Cidr {
      get { return cidr_; }
      set {
        cidr_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "host" field.</summary>
    public const int HostFieldNumber = 3;
    private string host_ = "";
    /// <summary>
    /// host name
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Host {
      get { return host_; }
      set {
        host_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "os" field.</summary>
    public const int OsFieldNumber = 4;
    private string os_ = "";
    /// <summary>
    /// host os
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Os {
      get { return os_; }
      set {
        os_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "computerName" field.</summary>
    public const int ComputerNameFieldNumber = 5;
    private string computerName_ = "";
    /// <summary>
    /// host computer name
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string ComputerName {
      get { return computerName_; }
      set {
        computerName_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "signalServerHost" field.</summary>
    public const int SignalServerHostFieldNumber = 6;
    private string signalServerHost_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string SignalServerHost {
      get { return signalServerHost_; }
      set {
        signalServerHost_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "signalServerPort" field.</summary>
    public const int SignalServerPortFieldNumber = 7;
    private ulong signalServerPort_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ulong SignalServerPort {
      get { return signalServerPort_; }
      set {
        signalServerPort_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as LoginSessionResponse);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(LoginSessionResponse other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if(!ip_.Equals(other.ip_)) return false;
      if (Cidr != other.Cidr) return false;
      if (Host != other.Host) return false;
      if (Os != other.Os) return false;
      if (ComputerName != other.ComputerName) return false;
      if (SignalServerHost != other.SignalServerHost) return false;
      if (SignalServerPort != other.SignalServerPort) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= ip_.GetHashCode();
      if (Cidr.Length != 0) hash ^= Cidr.GetHashCode();
      if (Host.Length != 0) hash ^= Host.GetHashCode();
      if (Os.Length != 0) hash ^= Os.GetHashCode();
      if (ComputerName.Length != 0) hash ^= ComputerName.GetHashCode();
      if (SignalServerHost.Length != 0) hash ^= SignalServerHost.GetHashCode();
      if (SignalServerPort != 0UL) hash ^= SignalServerPort.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      ip_.WriteTo(output, _repeated_ip_codec);
      if (Cidr.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Cidr);
      }
      if (Host.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(Host);
      }
      if (Os.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(Os);
      }
      if (ComputerName.Length != 0) {
        output.WriteRawTag(42);
        output.WriteString(ComputerName);
      }
      if (SignalServerHost.Length != 0) {
        output.WriteRawTag(50);
        output.WriteString(SignalServerHost);
      }
      if (SignalServerPort != 0UL) {
        output.WriteRawTag(56);
        output.WriteUInt64(SignalServerPort);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      ip_.WriteTo(ref output, _repeated_ip_codec);
      if (Cidr.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Cidr);
      }
      if (Host.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(Host);
      }
      if (Os.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(Os);
      }
      if (ComputerName.Length != 0) {
        output.WriteRawTag(42);
        output.WriteString(ComputerName);
      }
      if (SignalServerHost.Length != 0) {
        output.WriteRawTag(50);
        output.WriteString(SignalServerHost);
      }
      if (SignalServerPort != 0UL) {
        output.WriteRawTag(56);
        output.WriteUInt64(SignalServerPort);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      size += ip_.CalculateSize(_repeated_ip_codec);
      if (Cidr.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Cidr);
      }
      if (Host.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Host);
      }
      if (Os.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Os);
      }
      if (ComputerName.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(ComputerName);
      }
      if (SignalServerHost.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(SignalServerHost);
      }
      if (SignalServerPort != 0UL) {
        size += 1 + pb::CodedOutputStream.ComputeUInt64Size(SignalServerPort);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(LoginSessionResponse other) {
      if (other == null) {
        return;
      }
      ip_.Add(other.ip_);
      if (other.Cidr.Length != 0) {
        Cidr = other.Cidr;
      }
      if (other.Host.Length != 0) {
        Host = other.Host;
      }
      if (other.Os.Length != 0) {
        Os = other.Os;
      }
      if (other.ComputerName.Length != 0) {
        ComputerName = other.ComputerName;
      }
      if (other.SignalServerHost.Length != 0) {
        SignalServerHost = other.SignalServerHost;
      }
      if (other.SignalServerPort != 0UL) {
        SignalServerPort = other.SignalServerPort;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            ip_.AddEntriesFrom(input, _repeated_ip_codec);
            break;
          }
          case 18: {
            Cidr = input.ReadString();
            break;
          }
          case 26: {
            Host = input.ReadString();
            break;
          }
          case 34: {
            Os = input.ReadString();
            break;
          }
          case 42: {
            ComputerName = input.ReadString();
            break;
          }
          case 50: {
            SignalServerHost = input.ReadString();
            break;
          }
          case 56: {
            SignalServerPort = input.ReadUInt64();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            ip_.AddEntriesFrom(ref input, _repeated_ip_codec);
            break;
          }
          case 18: {
            Cidr = input.ReadString();
            break;
          }
          case 26: {
            Host = input.ReadString();
            break;
          }
          case 34: {
            Os = input.ReadString();
            break;
          }
          case 42: {
            ComputerName = input.ReadString();
            break;
          }
          case 50: {
            SignalServerHost = input.ReadString();
            break;
          }
          case 56: {
            SignalServerPort = input.ReadUInt64();
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class GetInvitationRequest : pb::IMessage<GetInvitationRequest>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<GetInvitationRequest> _parser = new pb::MessageParser<GetInvitationRequest>(() => new GetInvitationRequest());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<GetInvitationRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Protos.LoginReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public GetInvitationRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public GetInvitationRequest(GetInvitationRequest other) : this() {
      inviteCode_ = other.inviteCode_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public GetInvitationRequest Clone() {
      return new GetInvitationRequest(this);
    }

    /// <summary>Field number for the "inviteCode" field.</summary>
    public const int InviteCodeFieldNumber = 1;
    private string inviteCode_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string InviteCode {
      get { return inviteCode_; }
      set {
        inviteCode_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as GetInvitationRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(GetInvitationRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (InviteCode != other.InviteCode) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (InviteCode.Length != 0) hash ^= InviteCode.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (InviteCode.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(InviteCode);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (InviteCode.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(InviteCode);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (InviteCode.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(InviteCode);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(GetInvitationRequest other) {
      if (other == null) {
        return;
      }
      if (other.InviteCode.Length != 0) {
        InviteCode = other.InviteCode;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            InviteCode = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            InviteCode = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class GetInvitationResponse : pb::IMessage<GetInvitationResponse>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<GetInvitationResponse> _parser = new pb::MessageParser<GetInvitationResponse>(() => new GetInvitationResponse());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<GetInvitationResponse> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Protos.LoginReflection.Descriptor.MessageTypes[3]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public GetInvitationResponse() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public GetInvitationResponse(GetInvitationResponse other) : this() {
      email_ = other.email_;
      inviteCode_ = other.inviteCode_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public GetInvitationResponse Clone() {
      return new GetInvitationResponse(this);
    }

    /// <summary>Field number for the "email" field.</summary>
    public const int EmailFieldNumber = 1;
    private string email_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Email {
      get { return email_; }
      set {
        email_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "inviteCode" field.</summary>
    public const int InviteCodeFieldNumber = 2;
    private string inviteCode_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string InviteCode {
      get { return inviteCode_; }
      set {
        inviteCode_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as GetInvitationResponse);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(GetInvitationResponse other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Email != other.Email) return false;
      if (InviteCode != other.InviteCode) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Email.Length != 0) hash ^= Email.GetHashCode();
      if (InviteCode.Length != 0) hash ^= InviteCode.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Email.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Email);
      }
      if (InviteCode.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(InviteCode);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Email.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Email);
      }
      if (InviteCode.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(InviteCode);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Email.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Email);
      }
      if (InviteCode.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(InviteCode);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(GetInvitationResponse other) {
      if (other == null) {
        return;
      }
      if (other.Email.Length != 0) {
        Email = other.Email;
      }
      if (other.InviteCode.Length != 0) {
        InviteCode = other.InviteCode;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Email = input.ReadString();
            break;
          }
          case 18: {
            InviteCode = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            Email = input.ReadString();
            break;
          }
          case 18: {
            InviteCode = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
