// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: runetale/runetale/v1/log_reader.proto
// </auto-generated>
#pragma warning disable 0414, 1591, 8981, 0612
#region Designer generated code

using grpc = global::Grpc.Core;

namespace Logserver {
  /// <summary>
  /// LogReaderService provides log query APIs for administrators and internal services.
  /// Authentication: gRPC metadata "x-api-key" header.
  /// Queries are based on log_stream_id (PublicID = SHA-256 of PrivateID).
  /// </summary>
  public static partial class LogReaderService
  {
    static readonly string __ServiceName = "logserver.LogReaderService";

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static void __Helper_SerializeMessage(global::Google.Protobuf.IMessage message, grpc::SerializationContext context)
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (message is global::Google.Protobuf.IBufferMessage)
      {
        context.SetPayloadLength(message.CalculateSize());
        global::Google.Protobuf.MessageExtensions.WriteTo(message, context.GetBufferWriter());
        context.Complete();
        return;
      }
      #endif
      context.Complete(global::Google.Protobuf.MessageExtensions.ToByteArray(message));
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static class __Helper_MessageCache<T>
    {
      public static readonly bool IsBufferMessage = global::System.Reflection.IntrospectionExtensions.GetTypeInfo(typeof(global::Google.Protobuf.IBufferMessage)).IsAssignableFrom(typeof(T));
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static T __Helper_DeserializeMessage<T>(grpc::DeserializationContext context, global::Google.Protobuf.MessageParser<T> parser) where T : global::Google.Protobuf.IMessage<T>
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (__Helper_MessageCache<T>.IsBufferMessage)
      {
        return parser.ParseFrom(context.PayloadAsReadOnlySequence());
      }
      #endif
      return parser.ParseFrom(context.PayloadAsNewBuffer());
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Logserver.GetLoglyphRequest> __Marshaller_logserver_GetLoglyphRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Logserver.GetLoglyphRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Logserver.GetLoglyphResponse> __Marshaller_logserver_GetLoglyphResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Logserver.GetLoglyphResponse.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Logserver.GetOrbitEventsRequest> __Marshaller_logserver_GetOrbitEventsRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Logserver.GetOrbitEventsRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Logserver.GetOrbitEventsResponse> __Marshaller_logserver_GetOrbitEventsResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Logserver.GetOrbitEventsResponse.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Logserver.GetOrbitDailyCountsRequest> __Marshaller_logserver_GetOrbitDailyCountsRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Logserver.GetOrbitDailyCountsRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Logserver.GetOrbitDailyCountsResponse> __Marshaller_logserver_GetOrbitDailyCountsResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Logserver.GetOrbitDailyCountsResponse.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Logserver.GetPacketFlowLogsRequest> __Marshaller_logserver_GetPacketFlowLogsRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Logserver.GetPacketFlowLogsRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Logserver.GetPacketFlowLogsResponse> __Marshaller_logserver_GetPacketFlowLogsResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Logserver.GetPacketFlowLogsResponse.Parser));

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::Logserver.GetLoglyphRequest, global::Logserver.GetLoglyphResponse> __Method_GetLoglyphEntries = new grpc::Method<global::Logserver.GetLoglyphRequest, global::Logserver.GetLoglyphResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "GetLoglyphEntries",
        __Marshaller_logserver_GetLoglyphRequest,
        __Marshaller_logserver_GetLoglyphResponse);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::Logserver.GetOrbitEventsRequest, global::Logserver.GetOrbitEventsResponse> __Method_GetOrbitEvents = new grpc::Method<global::Logserver.GetOrbitEventsRequest, global::Logserver.GetOrbitEventsResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "GetOrbitEvents",
        __Marshaller_logserver_GetOrbitEventsRequest,
        __Marshaller_logserver_GetOrbitEventsResponse);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::Logserver.GetOrbitDailyCountsRequest, global::Logserver.GetOrbitDailyCountsResponse> __Method_GetOrbitDailyCounts = new grpc::Method<global::Logserver.GetOrbitDailyCountsRequest, global::Logserver.GetOrbitDailyCountsResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "GetOrbitDailyCounts",
        __Marshaller_logserver_GetOrbitDailyCountsRequest,
        __Marshaller_logserver_GetOrbitDailyCountsResponse);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::Logserver.GetPacketFlowLogsRequest, global::Logserver.GetPacketFlowLogsResponse> __Method_GetPacketFlowLogs = new grpc::Method<global::Logserver.GetPacketFlowLogsRequest, global::Logserver.GetPacketFlowLogsResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "GetPacketFlowLogs",
        __Marshaller_logserver_GetPacketFlowLogsRequest,
        __Marshaller_logserver_GetPacketFlowLogsResponse);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::Logserver.LogReaderReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of LogReaderService</summary>
    [grpc::BindServiceMethod(typeof(LogReaderService), "BindService")]
    public abstract partial class LogReaderServiceBase
    {
      /// <summary>
      /// GetLoglyphEntries retrieves client debug log entries.
      /// </summary>
      /// <param name="request">The request received from the client.</param>
      /// <param name="context">The context of the server-side call handler being invoked.</param>
      /// <returns>The response to send back to the client (wrapped by a task).</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::Logserver.GetLoglyphResponse> GetLoglyphEntries(global::Logserver.GetLoglyphRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      /// <summary>
      /// GetOrbitEvents retrieves stored telemetry events.
      /// </summary>
      /// <param name="request">The request received from the client.</param>
      /// <param name="context">The context of the server-side call handler being invoked.</param>
      /// <returns>The response to send back to the client (wrapped by a task).</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::Logserver.GetOrbitEventsResponse> GetOrbitEvents(global::Logserver.GetOrbitEventsRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      /// <summary>
      /// GetOrbitDailyCounts retrieves aggregated daily telemetry counts.
      /// </summary>
      /// <param name="request">The request received from the client.</param>
      /// <param name="context">The context of the server-side call handler being invoked.</param>
      /// <returns>The response to send back to the client (wrapped by a task).</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::Logserver.GetOrbitDailyCountsResponse> GetOrbitDailyCounts(global::Logserver.GetOrbitDailyCountsRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      /// <summary>
      /// GetPacketFlowLogs retrieves network flow statistics.
      /// </summary>
      /// <param name="request">The request received from the client.</param>
      /// <param name="context">The context of the server-side call handler being invoked.</param>
      /// <returns>The response to send back to the client (wrapped by a task).</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::Logserver.GetPacketFlowLogsResponse> GetPacketFlowLogs(global::Logserver.GetPacketFlowLogsRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for LogReaderService</summary>
    public partial class LogReaderServiceClient : grpc::ClientBase<LogReaderServiceClient>
    {
      /// <summary>Creates a new client for LogReaderService</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public LogReaderServiceClient(grpc::ChannelBase channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for LogReaderService that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public LogReaderServiceClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      protected LogReaderServiceClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      protected LogReaderServiceClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      /// <summary>
      /// GetLoglyphEntries retrieves client debug log entries.
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The response received from the server.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Logserver.GetLoglyphResponse GetLoglyphEntries(global::Logserver.GetLoglyphRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetLoglyphEntries(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// GetLoglyphEntries retrieves client debug log entries.
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The response received from the server.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Logserver.GetLoglyphResponse GetLoglyphEntries(global::Logserver.GetLoglyphRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_GetLoglyphEntries, null, options, request);
      }
      /// <summary>
      /// GetLoglyphEntries retrieves client debug log entries.
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The call object.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Logserver.GetLoglyphResponse> GetLoglyphEntriesAsync(global::Logserver.GetLoglyphRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetLoglyphEntriesAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// GetLoglyphEntries retrieves client debug log entries.
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The call object.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Logserver.GetLoglyphResponse> GetLoglyphEntriesAsync(global::Logserver.GetLoglyphRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_GetLoglyphEntries, null, options, request);
      }
      /// <summary>
      /// GetOrbitEvents retrieves stored telemetry events.
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The response received from the server.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Logserver.GetOrbitEventsResponse GetOrbitEvents(global::Logserver.GetOrbitEventsRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetOrbitEvents(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// GetOrbitEvents retrieves stored telemetry events.
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The response received from the server.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Logserver.GetOrbitEventsResponse GetOrbitEvents(global::Logserver.GetOrbitEventsRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_GetOrbitEvents, null, options, request);
      }
      /// <summary>
      /// GetOrbitEvents retrieves stored telemetry events.
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The call object.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Logserver.GetOrbitEventsResponse> GetOrbitEventsAsync(global::Logserver.GetOrbitEventsRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetOrbitEventsAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// GetOrbitEvents retrieves stored telemetry events.
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The call object.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Logserver.GetOrbitEventsResponse> GetOrbitEventsAsync(global::Logserver.GetOrbitEventsRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_GetOrbitEvents, null, options, request);
      }
      /// <summary>
      /// GetOrbitDailyCounts retrieves aggregated daily telemetry counts.
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The response received from the server.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Logserver.GetOrbitDailyCountsResponse GetOrbitDailyCounts(global::Logserver.GetOrbitDailyCountsRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetOrbitDailyCounts(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// GetOrbitDailyCounts retrieves aggregated daily telemetry counts.
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The response received from the server.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Logserver.GetOrbitDailyCountsResponse GetOrbitDailyCounts(global::Logserver.GetOrbitDailyCountsRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_GetOrbitDailyCounts, null, options, request);
      }
      /// <summary>
      /// GetOrbitDailyCounts retrieves aggregated daily telemetry counts.
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The call object.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Logserver.GetOrbitDailyCountsResponse> GetOrbitDailyCountsAsync(global::Logserver.GetOrbitDailyCountsRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetOrbitDailyCountsAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// GetOrbitDailyCounts retrieves aggregated daily telemetry counts.
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The call object.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Logserver.GetOrbitDailyCountsResponse> GetOrbitDailyCountsAsync(global::Logserver.GetOrbitDailyCountsRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_GetOrbitDailyCounts, null, options, request);
      }
      /// <summary>
      /// GetPacketFlowLogs retrieves network flow statistics.
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The response received from the server.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Logserver.GetPacketFlowLogsResponse GetPacketFlowLogs(global::Logserver.GetPacketFlowLogsRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetPacketFlowLogs(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// GetPacketFlowLogs retrieves network flow statistics.
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The response received from the server.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Logserver.GetPacketFlowLogsResponse GetPacketFlowLogs(global::Logserver.GetPacketFlowLogsRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_GetPacketFlowLogs, null, options, request);
      }
      /// <summary>
      /// GetPacketFlowLogs retrieves network flow statistics.
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The call object.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Logserver.GetPacketFlowLogsResponse> GetPacketFlowLogsAsync(global::Logserver.GetPacketFlowLogsRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetPacketFlowLogsAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// GetPacketFlowLogs retrieves network flow statistics.
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The call object.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Logserver.GetPacketFlowLogsResponse> GetPacketFlowLogsAsync(global::Logserver.GetPacketFlowLogsRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_GetPacketFlowLogs, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      protected override LogReaderServiceClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new LogReaderServiceClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    public static grpc::ServerServiceDefinition BindService(LogReaderServiceBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_GetLoglyphEntries, serviceImpl.GetLoglyphEntries)
          .AddMethod(__Method_GetOrbitEvents, serviceImpl.GetOrbitEvents)
          .AddMethod(__Method_GetOrbitDailyCounts, serviceImpl.GetOrbitDailyCounts)
          .AddMethod(__Method_GetPacketFlowLogs, serviceImpl.GetPacketFlowLogs).Build();
    }

    /// <summary>Register service method with a service binder with or without implementation. Useful when customizing the service binding logic.
    /// Note: this method is part of an experimental API that can change or be removed without any prior notice.</summary>
    /// <param name="serviceBinder">Service methods will be bound by calling <c>AddMethod</c> on this object.</param>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    public static void BindService(grpc::ServiceBinderBase serviceBinder, LogReaderServiceBase serviceImpl)
    {
      serviceBinder.AddMethod(__Method_GetLoglyphEntries, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Logserver.GetLoglyphRequest, global::Logserver.GetLoglyphResponse>(serviceImpl.GetLoglyphEntries));
      serviceBinder.AddMethod(__Method_GetOrbitEvents, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Logserver.GetOrbitEventsRequest, global::Logserver.GetOrbitEventsResponse>(serviceImpl.GetOrbitEvents));
      serviceBinder.AddMethod(__Method_GetOrbitDailyCounts, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Logserver.GetOrbitDailyCountsRequest, global::Logserver.GetOrbitDailyCountsResponse>(serviceImpl.GetOrbitDailyCounts));
      serviceBinder.AddMethod(__Method_GetPacketFlowLogs, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Logserver.GetPacketFlowLogsRequest, global::Logserver.GetPacketFlowLogsResponse>(serviceImpl.GetPacketFlowLogs));
    }

  }
}
#endregion
