// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: runetale/runetale/v1/log_stats.proto
// </auto-generated>
#pragma warning disable 0414, 1591, 8981, 0612
#region Designer generated code

using grpc = global::Grpc.Core;

namespace Logserver {
  /// <summary>
  /// LogStatsService provides aggregated traffic statistics for MSP integrations.
  /// Authentication: gRPC metadata "authorization" header with Bearer JWT token.
  /// Queries are based on domain_telemetry_log_id (tenant-level identifier).
  /// </summary>
  public static partial class LogStatsService
  {
    static readonly string __ServiceName = "logserver.LogStatsService";

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static void __Helper_SerializeMessage(global::Google.Protobuf.IMessage message, grpc::SerializationContext context)
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (message is global::Google.Protobuf.IBufferMessage)
      {
        context.SetPayloadLength(message.CalculateSize());
        global::Google.Protobuf.MessageExtensions.WriteTo(message, context.GetBufferWriter());
        context.Complete();
        return;
      }
      #endif
      context.Complete(global::Google.Protobuf.MessageExtensions.ToByteArray(message));
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static class __Helper_MessageCache<T>
    {
      public static readonly bool IsBufferMessage = global::System.Reflection.IntrospectionExtensions.GetTypeInfo(typeof(global::Google.Protobuf.IBufferMessage)).IsAssignableFrom(typeof(T));
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static T __Helper_DeserializeMessage<T>(grpc::DeserializationContext context, global::Google.Protobuf.MessageParser<T> parser) where T : global::Google.Protobuf.IMessage<T>
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (__Helper_MessageCache<T>.IsBufferMessage)
      {
        return parser.ParseFrom(context.PayloadAsReadOnlySequence());
      }
      #endif
      return parser.ParseFrom(context.PayloadAsNewBuffer());
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Logserver.GetTenantTrafficSummaryRequest> __Marshaller_logserver_GetTenantTrafficSummaryRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Logserver.GetTenantTrafficSummaryRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Logserver.GetTenantTrafficSummaryResponse> __Marshaller_logserver_GetTenantTrafficSummaryResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Logserver.GetTenantTrafficSummaryResponse.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Logserver.GetTenantTrafficSummariesRequest> __Marshaller_logserver_GetTenantTrafficSummariesRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Logserver.GetTenantTrafficSummariesRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Logserver.GetTenantTrafficSummariesResponse> __Marshaller_logserver_GetTenantTrafficSummariesResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Logserver.GetTenantTrafficSummariesResponse.Parser));

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::Logserver.GetTenantTrafficSummaryRequest, global::Logserver.GetTenantTrafficSummaryResponse> __Method_GetTenantTrafficSummary = new grpc::Method<global::Logserver.GetTenantTrafficSummaryRequest, global::Logserver.GetTenantTrafficSummaryResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "GetTenantTrafficSummary",
        __Marshaller_logserver_GetTenantTrafficSummaryRequest,
        __Marshaller_logserver_GetTenantTrafficSummaryResponse);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::Logserver.GetTenantTrafficSummariesRequest, global::Logserver.GetTenantTrafficSummariesResponse> __Method_GetTenantTrafficSummaries = new grpc::Method<global::Logserver.GetTenantTrafficSummariesRequest, global::Logserver.GetTenantTrafficSummariesResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "GetTenantTrafficSummaries",
        __Marshaller_logserver_GetTenantTrafficSummariesRequest,
        __Marshaller_logserver_GetTenantTrafficSummariesResponse);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::Logserver.LogStatsReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of LogStatsService</summary>
    [grpc::BindServiceMethod(typeof(LogStatsService), "BindService")]
    public abstract partial class LogStatsServiceBase
    {
      /// <summary>
      /// GetTenantTrafficSummary returns aggregated traffic bytes for a single tenant.
      /// </summary>
      /// <param name="request">The request received from the client.</param>
      /// <param name="context">The context of the server-side call handler being invoked.</param>
      /// <returns>The response to send back to the client (wrapped by a task).</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::Logserver.GetTenantTrafficSummaryResponse> GetTenantTrafficSummary(global::Logserver.GetTenantTrafficSummaryRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      /// <summary>
      /// GetTenantTrafficSummaries returns aggregated traffic bytes for multiple tenants in one call.
      /// Used by MSP to aggregate stats across parent + child tenants.
      /// </summary>
      /// <param name="request">The request received from the client.</param>
      /// <param name="context">The context of the server-side call handler being invoked.</param>
      /// <returns>The response to send back to the client (wrapped by a task).</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::Logserver.GetTenantTrafficSummariesResponse> GetTenantTrafficSummaries(global::Logserver.GetTenantTrafficSummariesRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for LogStatsService</summary>
    public partial class LogStatsServiceClient : grpc::ClientBase<LogStatsServiceClient>
    {
      /// <summary>Creates a new client for LogStatsService</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public LogStatsServiceClient(grpc::ChannelBase channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for LogStatsService that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public LogStatsServiceClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      protected LogStatsServiceClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      protected LogStatsServiceClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      /// <summary>
      /// GetTenantTrafficSummary returns aggregated traffic bytes for a single tenant.
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The response received from the server.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Logserver.GetTenantTrafficSummaryResponse GetTenantTrafficSummary(global::Logserver.GetTenantTrafficSummaryRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetTenantTrafficSummary(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// GetTenantTrafficSummary returns aggregated traffic bytes for a single tenant.
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The response received from the server.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Logserver.GetTenantTrafficSummaryResponse GetTenantTrafficSummary(global::Logserver.GetTenantTrafficSummaryRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_GetTenantTrafficSummary, null, options, request);
      }
      /// <summary>
      /// GetTenantTrafficSummary returns aggregated traffic bytes for a single tenant.
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The call object.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Logserver.GetTenantTrafficSummaryResponse> GetTenantTrafficSummaryAsync(global::Logserver.GetTenantTrafficSummaryRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetTenantTrafficSummaryAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// GetTenantTrafficSummary returns aggregated traffic bytes for a single tenant.
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The call object.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Logserver.GetTenantTrafficSummaryResponse> GetTenantTrafficSummaryAsync(global::Logserver.GetTenantTrafficSummaryRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_GetTenantTrafficSummary, null, options, request);
      }
      /// <summary>
      /// GetTenantTrafficSummaries returns aggregated traffic bytes for multiple tenants in one call.
      /// Used by MSP to aggregate stats across parent + child tenants.
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The response received from the server.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Logserver.GetTenantTrafficSummariesResponse GetTenantTrafficSummaries(global::Logserver.GetTenantTrafficSummariesRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetTenantTrafficSummaries(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// GetTenantTrafficSummaries returns aggregated traffic bytes for multiple tenants in one call.
      /// Used by MSP to aggregate stats across parent + child tenants.
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The response received from the server.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Logserver.GetTenantTrafficSummariesResponse GetTenantTrafficSummaries(global::Logserver.GetTenantTrafficSummariesRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_GetTenantTrafficSummaries, null, options, request);
      }
      /// <summary>
      /// GetTenantTrafficSummaries returns aggregated traffic bytes for multiple tenants in one call.
      /// Used by MSP to aggregate stats across parent + child tenants.
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The call object.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Logserver.GetTenantTrafficSummariesResponse> GetTenantTrafficSummariesAsync(global::Logserver.GetTenantTrafficSummariesRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetTenantTrafficSummariesAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// GetTenantTrafficSummaries returns aggregated traffic bytes for multiple tenants in one call.
      /// Used by MSP to aggregate stats across parent + child tenants.
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The call object.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Logserver.GetTenantTrafficSummariesResponse> GetTenantTrafficSummariesAsync(global::Logserver.GetTenantTrafficSummariesRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_GetTenantTrafficSummaries, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      protected override LogStatsServiceClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new LogStatsServiceClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    public static grpc::ServerServiceDefinition BindService(LogStatsServiceBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_GetTenantTrafficSummary, serviceImpl.GetTenantTrafficSummary)
          .AddMethod(__Method_GetTenantTrafficSummaries, serviceImpl.GetTenantTrafficSummaries).Build();
    }

    /// <summary>Register service method with a service binder with or without implementation. Useful when customizing the service binding logic.
    /// Note: this method is part of an experimental API that can change or be removed without any prior notice.</summary>
    /// <param name="serviceBinder">Service methods will be bound by calling <c>AddMethod</c> on this object.</param>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    public static void BindService(grpc::ServiceBinderBase serviceBinder, LogStatsServiceBase serviceImpl)
    {
      serviceBinder.AddMethod(__Method_GetTenantTrafficSummary, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Logserver.GetTenantTrafficSummaryRequest, global::Logserver.GetTenantTrafficSummaryResponse>(serviceImpl.GetTenantTrafficSummary));
      serviceBinder.AddMethod(__Method_GetTenantTrafficSummaries, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Logserver.GetTenantTrafficSummariesRequest, global::Logserver.GetTenantTrafficSummariesResponse>(serviceImpl.GetTenantTrafficSummaries));
    }

  }
}
#endregion
