// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: runetale/runetale/v1/log_writer.proto
// </auto-generated>
#pragma warning disable 0414, 1591, 8981, 0612
#region Designer generated code

using grpc = global::Grpc.Core;

namespace Logserver {
  /// <summary>
  /// LogWriterService receives log uploads from client nodes.
  /// Authentication: gRPC metadata "private-id" + "log-token" headers.
  /// The log server validates the token signature, checks expiration,
  /// and verifies that SHA-256(private-id) matches the token's public_id.
  /// </summary>
  public static partial class LogWriterService
  {
    static readonly string __ServiceName = "logserver.LogWriterService";

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static void __Helper_SerializeMessage(global::Google.Protobuf.IMessage message, grpc::SerializationContext context)
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (message is global::Google.Protobuf.IBufferMessage)
      {
        context.SetPayloadLength(message.CalculateSize());
        global::Google.Protobuf.MessageExtensions.WriteTo(message, context.GetBufferWriter());
        context.Complete();
        return;
      }
      #endif
      context.Complete(global::Google.Protobuf.MessageExtensions.ToByteArray(message));
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static class __Helper_MessageCache<T>
    {
      public static readonly bool IsBufferMessage = global::System.Reflection.IntrospectionExtensions.GetTypeInfo(typeof(global::Google.Protobuf.IBufferMessage)).IsAssignableFrom(typeof(T));
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static T __Helper_DeserializeMessage<T>(grpc::DeserializationContext context, global::Google.Protobuf.MessageParser<T> parser) where T : global::Google.Protobuf.IMessage<T>
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (__Helper_MessageCache<T>.IsBufferMessage)
      {
        return parser.ParseFrom(context.PayloadAsReadOnlySequence());
      }
      #endif
      return parser.ParseFrom(context.PayloadAsNewBuffer());
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Logserver.LoglyphUploadRequest> __Marshaller_logserver_LoglyphUploadRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Logserver.LoglyphUploadRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Logserver.LoglyphUploadResponse> __Marshaller_logserver_LoglyphUploadResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Logserver.LoglyphUploadResponse.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Logserver.OrbitBatchUploadRequest> __Marshaller_logserver_OrbitBatchUploadRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Logserver.OrbitBatchUploadRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Logserver.OrbitBatchUploadResponse> __Marshaller_logserver_OrbitBatchUploadResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Logserver.OrbitBatchUploadResponse.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Logserver.PacketFlowLogUploadRequest> __Marshaller_logserver_PacketFlowLogUploadRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Logserver.PacketFlowLogUploadRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Logserver.PacketFlowLogUploadResponse> __Marshaller_logserver_PacketFlowLogUploadResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Logserver.PacketFlowLogUploadResponse.Parser));

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::Logserver.LoglyphUploadRequest, global::Logserver.LoglyphUploadResponse> __Method_UploadLoglyphEntries = new grpc::Method<global::Logserver.LoglyphUploadRequest, global::Logserver.LoglyphUploadResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "UploadLoglyphEntries",
        __Marshaller_logserver_LoglyphUploadRequest,
        __Marshaller_logserver_LoglyphUploadResponse);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::Logserver.OrbitBatchUploadRequest, global::Logserver.OrbitBatchUploadResponse> __Method_UploadOrbitBatch = new grpc::Method<global::Logserver.OrbitBatchUploadRequest, global::Logserver.OrbitBatchUploadResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "UploadOrbitBatch",
        __Marshaller_logserver_OrbitBatchUploadRequest,
        __Marshaller_logserver_OrbitBatchUploadResponse);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::Logserver.PacketFlowLogUploadRequest, global::Logserver.PacketFlowLogUploadResponse> __Method_UploadPacketFlowLogs = new grpc::Method<global::Logserver.PacketFlowLogUploadRequest, global::Logserver.PacketFlowLogUploadResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "UploadPacketFlowLogs",
        __Marshaller_logserver_PacketFlowLogUploadRequest,
        __Marshaller_logserver_PacketFlowLogUploadResponse);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::Logserver.LogWriterReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of LogWriterService</summary>
    [grpc::BindServiceMethod(typeof(LogWriterService), "BindService")]
    public abstract partial class LogWriterServiceBase
    {
      /// <summary>
      /// UploadLoglyphEntries uploads client debug log entries.
      /// </summary>
      /// <param name="request">The request received from the client.</param>
      /// <param name="context">The context of the server-side call handler being invoked.</param>
      /// <returns>The response to send back to the client (wrapped by a task).</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::Logserver.LoglyphUploadResponse> UploadLoglyphEntries(global::Logserver.LoglyphUploadRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      /// <summary>
      /// UploadOrbitBatch uploads a batch of telemetry events.
      /// </summary>
      /// <param name="request">The request received from the client.</param>
      /// <param name="context">The context of the server-side call handler being invoked.</param>
      /// <returns>The response to send back to the client (wrapped by a task).</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::Logserver.OrbitBatchUploadResponse> UploadOrbitBatch(global::Logserver.OrbitBatchUploadRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      /// <summary>
      /// UploadPacketFlowLogs uploads network flow statistics.
      /// </summary>
      /// <param name="request">The request received from the client.</param>
      /// <param name="context">The context of the server-side call handler being invoked.</param>
      /// <returns>The response to send back to the client (wrapped by a task).</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::Logserver.PacketFlowLogUploadResponse> UploadPacketFlowLogs(global::Logserver.PacketFlowLogUploadRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for LogWriterService</summary>
    public partial class LogWriterServiceClient : grpc::ClientBase<LogWriterServiceClient>
    {
      /// <summary>Creates a new client for LogWriterService</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public LogWriterServiceClient(grpc::ChannelBase channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for LogWriterService that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public LogWriterServiceClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      protected LogWriterServiceClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      protected LogWriterServiceClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      /// <summary>
      /// UploadLoglyphEntries uploads client debug log entries.
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The response received from the server.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Logserver.LoglyphUploadResponse UploadLoglyphEntries(global::Logserver.LoglyphUploadRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return UploadLoglyphEntries(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// UploadLoglyphEntries uploads client debug log entries.
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The response received from the server.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Logserver.LoglyphUploadResponse UploadLoglyphEntries(global::Logserver.LoglyphUploadRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_UploadLoglyphEntries, null, options, request);
      }
      /// <summary>
      /// UploadLoglyphEntries uploads client debug log entries.
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The call object.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Logserver.LoglyphUploadResponse> UploadLoglyphEntriesAsync(global::Logserver.LoglyphUploadRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return UploadLoglyphEntriesAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// UploadLoglyphEntries uploads client debug log entries.
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The call object.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Logserver.LoglyphUploadResponse> UploadLoglyphEntriesAsync(global::Logserver.LoglyphUploadRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_UploadLoglyphEntries, null, options, request);
      }
      /// <summary>
      /// UploadOrbitBatch uploads a batch of telemetry events.
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The response received from the server.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Logserver.OrbitBatchUploadResponse UploadOrbitBatch(global::Logserver.OrbitBatchUploadRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return UploadOrbitBatch(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// UploadOrbitBatch uploads a batch of telemetry events.
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The response received from the server.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Logserver.OrbitBatchUploadResponse UploadOrbitBatch(global::Logserver.OrbitBatchUploadRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_UploadOrbitBatch, null, options, request);
      }
      /// <summary>
      /// UploadOrbitBatch uploads a batch of telemetry events.
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The call object.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Logserver.OrbitBatchUploadResponse> UploadOrbitBatchAsync(global::Logserver.OrbitBatchUploadRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return UploadOrbitBatchAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// UploadOrbitBatch uploads a batch of telemetry events.
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The call object.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Logserver.OrbitBatchUploadResponse> UploadOrbitBatchAsync(global::Logserver.OrbitBatchUploadRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_UploadOrbitBatch, null, options, request);
      }
      /// <summary>
      /// UploadPacketFlowLogs uploads network flow statistics.
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The response received from the server.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Logserver.PacketFlowLogUploadResponse UploadPacketFlowLogs(global::Logserver.PacketFlowLogUploadRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return UploadPacketFlowLogs(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// UploadPacketFlowLogs uploads network flow statistics.
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The response received from the server.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Logserver.PacketFlowLogUploadResponse UploadPacketFlowLogs(global::Logserver.PacketFlowLogUploadRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_UploadPacketFlowLogs, null, options, request);
      }
      /// <summary>
      /// UploadPacketFlowLogs uploads network flow statistics.
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The call object.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Logserver.PacketFlowLogUploadResponse> UploadPacketFlowLogsAsync(global::Logserver.PacketFlowLogUploadRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return UploadPacketFlowLogsAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// UploadPacketFlowLogs uploads network flow statistics.
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The call object.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Logserver.PacketFlowLogUploadResponse> UploadPacketFlowLogsAsync(global::Logserver.PacketFlowLogUploadRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_UploadPacketFlowLogs, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      protected override LogWriterServiceClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new LogWriterServiceClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    public static grpc::ServerServiceDefinition BindService(LogWriterServiceBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_UploadLoglyphEntries, serviceImpl.UploadLoglyphEntries)
          .AddMethod(__Method_UploadOrbitBatch, serviceImpl.UploadOrbitBatch)
          .AddMethod(__Method_UploadPacketFlowLogs, serviceImpl.UploadPacketFlowLogs).Build();
    }

    /// <summary>Register service method with a service binder with or without implementation. Useful when customizing the service binding logic.
    /// Note: this method is part of an experimental API that can change or be removed without any prior notice.</summary>
    /// <param name="serviceBinder">Service methods will be bound by calling <c>AddMethod</c> on this object.</param>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    public static void BindService(grpc::ServiceBinderBase serviceBinder, LogWriterServiceBase serviceImpl)
    {
      serviceBinder.AddMethod(__Method_UploadLoglyphEntries, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Logserver.LoglyphUploadRequest, global::Logserver.LoglyphUploadResponse>(serviceImpl.UploadLoglyphEntries));
      serviceBinder.AddMethod(__Method_UploadOrbitBatch, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Logserver.OrbitBatchUploadRequest, global::Logserver.OrbitBatchUploadResponse>(serviceImpl.UploadOrbitBatch));
      serviceBinder.AddMethod(__Method_UploadPacketFlowLogs, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Logserver.PacketFlowLogUploadRequest, global::Logserver.PacketFlowLogUploadResponse>(serviceImpl.UploadPacketFlowLogs));
    }

  }
}
#endregion
